"""holdings

Revision ID: f415e1d417d3
Revises: 4e420e2195c9
Create Date: 2026-06-21 08:51:00.060697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f415e1d417d3'
down_revision: Union[str, Sequence[str], None] = '4e420e2195c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_organization_id'), ['organization_id'], unique=False)

    op.create_table('holding_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('holding_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holding_id', 'project_id', name='uq_holding_project')
    )
    with op.batch_alter_table('holding_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holding_members_holding_id'), ['holding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holding_members_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holding_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holding_members_project_id'))
        batch_op.drop_index(batch_op.f('ix_holding_members_holding_id'))

    op.drop_table('holding_members')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_organization_id'))

    op.drop_table('holdings')
    # ### end Alembic commands ###
